### ISSUE TITLE
issue for special chacractor in parse dicom have Korean patient name

### ISSUE THREAD

**Issue by duongvtitleadpro** [rii-mango/Daikon#32]
i have trouble with korean, and patient name return have some special symbols. But when i used radiAnt application or dicom4che, result have not special symbol.
Reality: $)C김귀순
Expected: 김귀순
[filenameHQ.zip](https://github.com/rii-mango/Daikon/files/3696509/filenameHQ.zip)

**Comment by nickhingston** [comment]
Hi, I have just added support of ISO 2022 char sets including Korean on a branch on my fork:

https://github.com/nickhingston/Daikon.git on branch 20-chinese-garbled

it uses (a fork of) https://github.com/radialogica/dicom-character-set.git 

currently it breaks most of the tests, but i think just due to checksum sizes (which you'd expect may change).  It certainly decodes your file ok i think...

**Comment by nickhingston** [comment]
fixed in PR #33

**Comment by neurolabusc** [comment]
Thanks @nickhingston for solving this issue.
