### ISSUE TITLE
Unable to parse file with private tags.

### ISSUE THREAD

**Issue by rtdicomexplorer** [rii-mango/Daikon#49]
I find the library very cool, just I found out that is not able to parse DICOM files which contain private tags, when the transfer syntax is implicit. A example is attached.
[example.zip](https://github.com/rii-mango/Daikon/files/9608835/example.zip)

**Comment by rtdicomexplorer** [comment]
After careful investigation I discovered that the problem is represented by the Info Meta Header which is written in little endian implicit (very strange...). I'm currently testing a possible solution.

**Comment by neurolabusc** [comment]
@rtdicomexplorer this is not a valid Part 10 DICOM. Note the specification for the [DICOM File Meta Information](https://dicom.nema.org/dicom/2013/output/chtml/part10/chapter_7.html) which is **always** Explicit VR Little Endian Transfer Syntax regardless of the rest of the image. However, your file is missing the preamble (so it is a fragment, not a part 10 file). Further, it is missing the required File Meta Information Group Length.


Fortunately, gdcmconv is resilient to violations, and you can rescue this image as follows:

```
gdcmconv -w in.dcm out.dcm 
```

Since this is not a valid image, I am closing this issue.
